config/routes.rb
Rails.application.routes.draw do

  root 'welcome#home'

  resources :videos

end

app/models/video.rb
class Video < ActiveRecord::Base
  mount_uploader :video, VideoUploader

  before_validation :compute_hash, if: ->{ video.present? }
  validates :md5hash, uniqueness: true, on: :create
  validates :video, presence: true

  def compute_hash
    self.md5hash = Digest::MD5.hexdigest(video.read)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :load_video, only: %w(show)

  def create
    video = Video.new(video_attributes)
    if video.valid? && video.save!
      flash[:notice] = 'YEAH'
    else
      flash[:error] = video.errors.full_messages.join(', ')
    end
    redirect_to root_path
  end

  def show
  end

  private

  def load_video
    @video = Video.find(params[:id])
  end

  def video_attributes
    params.require(:video).permit(:video)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
    @videos = Video.all
    @video = Video.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Open Tube
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

    javascript:
      window.addEventListener('DOMContentLoaded', function(event) {
          videojs(video.getAttribute('id'), { preload: 'auto' }, function () {
             this.addClass('video-js');
             this.addClass('vjs-default-skin');
         });
      }, false);

  body

    .container
      - flash.each do |type, message|
        .alert.alert-dismissable role='status'
          a.close href="#" data-dismiss="alert" aria-hidden='true' ×
          = raw message

    = yield

app/views/videos/_form.slim
= form_for @video, :html => {:multipart => true} do |f|
  p
    = f.label :video
    = f.file_field :video, required: true

  = f.submit data: { disable_with: 'Uploading, please wait...' }

app/views/videos/show.slim
h1= @video.title
p
  #player
    video#video controls="controls" width="800" height="540"
      source src="#{@video.video.mp4}" type="video/mp4"
      / source src="client/medias/video_vo.webm" type="video/webm"
      / source src="client/medias/video_vo.ogv" type="video/ogg"

      / subtitles
      / track kind="captions" label="Français" src="client/captions/fr.srt" srclang="fr"

      / transcription
      / ul.transcriptlist
      /   li
      /     a href="mytrancriptFile.htm" title=("Transcription française - HTML - nouvelle fenêtre")  Transcription française - HTML
      /   li
      /     a href="server/transcriptions/fr.txt" title=("Transcription du sous-titrage - TXT")  Transcription du sous-titrage - TXT

    / audiodescription
    / audio hidden="hidden" preload="auto" src=""
    / audio hidden="hidden" preload="auto" src="client/medias/video_ad.mp3"

p= link_to 'Back', root_path

app/views/welcome/home.html.slim
h1 Welcome#home
p Find me in app/views/welcome/home.html.slim

= render partial: 'videos/form'

- if @current_video.present?
  hr
  p
    #player
      video#video controls="controls" height="480" width="640"
        source src="#{@current_video.video.mp4}" type="video/mp4"
        / source src="client/medias/video_vo.webm" type="video/webm"
        / source src="client/medias/video_vo.ogv" type="video/ogg"

        / subtitles
        / track kind="captions" label="Français" src="client/captions/fr.srt" srclang="fr"

        / transcription
        / ul.transcriptlist
        /   li
        /     a href="mytrancriptFile.htm" title=("Transcription française - HTML - nouvelle fenêtre")  Transcription française - HTML
        /   li
        /     a href="server/transcriptions/fr.txt" title=("Transcription du sous-titrage - TXT")  Transcription du sous-titrage - TXT

      / audiodescription
      / audio hidden="hidden" preload="auto" src=""
      / audio hidden="hidden" preload="auto" src="client/medias/video_ad.mp3"


hr
- @videos.each do |video|
  p
    strong= video.title
    br
    = link_to image_tag(video.video.thumb), video_path(video)